### ISSUE TITLE
AbstractRule name used before set on the MRO 

### ISSUE THREAD

**Issue by uvegla** [gabor-boros/hammurabi#216]
**Describe the bug**

An `AttributeError` for `name` is thrown for classes inheriting from `AbstractRule` when an exception - e.g. a parameter validation fails - occurs in the constructor. At that time we did not get to the point in the method resolution order to set the name parameter - set in `AbstractRule`.

**To Reproduce**

Let's imagine a custom precondition like:

```python
class ExamplePrecondition(Precondition):

    def __init__(self, param: str = '', **kwargs):
        stacks = self.validate(param, required=True)
        super().__init__(None, stacks, **kwargs)
```

Then the class is initialized without passing proper value for `param`:

```python
example = ExamplePrecondition()
```

In `AbstractRule` the validate will try to throw a `ValueError` and in the message, it calls `str(self)`. The `__str__` implementation of e.g. the `Precondition` class it tries to access `self.name` but at this point, it is not set causing the `AttributeError`.

**Expected behavior**

Either not rely on the name in the `__str__` implementations or play with the MRO to avoid this edge case. If possible, the original exception should not be masked or make it visible with a stack trace.

**System info**

 - OS: [e.g. macOS Mojave 10.15.6]
 - Hammurabi version: [e.g. 0.11.0]
 - Python version: [e.g. 3.8.5]

**Additional context**

The same exception hiding occurs when a required parameter is not set for rules and preconditions. For example, you do not pass the `match` parameter to `LineExists`.

**Comment by gabor-boros** [comment]
@uvegla Based on the nature of this issue, the problem exists in `__repr__` and every place where we rely on `name`, though other cases remained hidden. I have an easy fix for the `name` related issue and I'll push it later today.

**Comment by gabor-boros** [comment]
@uvegla Could you please test if the proposed fix solves the issue?

**Comment by uvegla** [comment]
@gabor-boros Thanks, it fixes the issue. Approved https://github.com/gabor-boros/hammurabi/pull/222. 🙇
